version: '3.8'
services:

    # PostgreSQL
    postgres:
        image: postgres:11-alpine
        container_name: backend-interview-db
        environment:
            POSTGRES_PASSWORD: 'secret'
            POSTGRES_USER: 'postgres'
            POSTGRES_DB: 'postgres'
        volumes:
            - ./migrations:/migrations
        expose:
            - 5432
        ports:
            - 5432:5432
